# Generated by Django 3.2.2 on 2021-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20210511_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=50),
        ),
    ]
